name: Code Checks

on:
  push:
    branches:
    - master
    - dev
  pull_request:
    branches:
    - master
    - dev

permissions: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - uses: actions/setup-python@v6
      with:
        python-version: "3.13"
    # Ref: https://github.com/tox-dev/action-pre-commit-uv
    - uses: tox-dev/action-pre-commit-uv@246b66536e366bb885f52d61983bf32f7c95e8b1 # v1.0.3

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v5
      with:
        persist-credentials: false
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[test]"

    - name: Pre-download 20 newsgroups
      shell: python
      run: |
        from sklearn.datasets import fetch_20newsgroups
        fetch_20newsgroups(subset="all", remove=("headers", "footers", "quotes"))

    - run: ls ~/scikit_learn_data/

    - name: Run Checking Mechanisms
      run: pytest --cov --numprocesses=auto --dist=loadscope
